# Site settings
title: 18F Consulting
description: > # this means to ignore newlines until "baseurl:"
  Welcome to 18F Consulting!
baseurl: "/consulting"
url: "https://pages.18f.gov"

# Header
header:
  logo_text: 18F Consulting
  logo_img: logo.svg
  # nav:
  #   - text: Article
  #     link: /example-article
  #   - text: About
  #     link: /about

# Edit pages
edit_page:
  # enabled: true  # Enabled by default for pages and posts
  text: "Improve this content »"
  github:
    author: 18F
    repo:   consulting
    branch: 18f-pages

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [hard_wrap, tables]

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: template/page
